---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.14.4
    app.quarkus.io/commit-id: 81a2a49bfb503420e37a0d04bef1cad6fce0d148
    app.quarkus.io/vcs-uri: https://github.com/ch007m/code-with-quarkus.git
    app.quarkus.io/build-timestamp: 2024-09-24 - 11:14:19 +0000
  labels:
    app.kubernetes.io/name: code-with-quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: code-with-quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: code-with-quarkus
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.14.4
        app.quarkus.io/commit-id: 81a2a49bfb503420e37a0d04bef1cad6fce0d148
        app.quarkus.io/vcs-uri: https://github.com/ch007m/code-with-quarkus.git
        app.quarkus.io/build-timestamp: 2024-09-24 - 11:14:19 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: code-with-quarkus
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: {{ .Values.app.image }}
          imagePullPolicy: Always
          name: code-with-quarkus
          ports:
            - containerPort: {{ .Values.app.ports.http }}
              name: http
              protocol: TCP
