---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.14.4
    app.quarkus.io/commit-id: 81a2a49bfb503420e37a0d04bef1cad6fce0d148
    app.quarkus.io/vcs-uri: https://github.com/ch007m/code-with-quarkus.git
    app.quarkus.io/build-timestamp: 2024-09-24 - 11:14:19 +0000
  labels:
    app.kubernetes.io/name: code-with-quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: code-with-quarkus
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.app.ports.http }}
  selector:
    app.kubernetes.io/name: code-with-quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
